### ISSUE TITLE
Add NSP to the checks

### ISSUE THREAD

**Issue by lholmquist** [inikulin/publish-please#1]
Would be nice to have nsp(https://github.com/nodesecurity/nsp) run as one of the checks.

I can add it if you think it would be useful

**Comment by inikulin** [comment]
It would be definetly great! PR is welcome. I think the separate optional validation will be nice. Could you add a brief summary on this feature in the readme, please? Because website for this thing is a little bit cryptic and it took some time for me to figure what's it for.

**Comment by lholmquist** [comment]
sure thing

**Comment by lholmquist** [comment]
PR here:  https://github.com/inikulin/publish-please/pull/4

**Comment by boneskull** [comment]
:+1:
