### ISSUE TITLE
Create "files" field in package.json on `init`

### ISSUE THREAD

**Issue by inikulin** [inikulin/publish-please#14]

**Comment by boneskull** [comment]
What's the purpose of this?

**Comment by inikulin** [comment]
There will be 'init' command which will guide through steps to setup publish-please for the given package. I'm constantly forget to add 'files' field, so my tests and other unecessary data gets published to npm. There will be a step in 'init' which will ask you to add that field to config. Further reading: https://github.com/inikulin/dmn#readme

**Comment by boneskull** [comment]
:+1:

**Comment by inikulin** [comment]
Closing in favor of #37
