### ISSUE TITLE
npm shrinkwrap validation?

### ISSUE THREAD

**Issue by zhuangya** [inikulin/publish-please#15]
maybe add npm shrinkwrap validation?

at least check the `version` in `npm-shrinkwrap.json` matches `version` in `package.json` and `git tag`

**Comment by inikulin** [comment]
I haven't used shrinkwrap. However, this sounds reasonable, but requires some additional investigation. Seems like it can be made as the part of version/tag validation if `npm-shrinkwrap.json` is present in the package.

**Comment by hdorgeval** [comment]
Hi @zhuangya, I close this issue in favor of [Vote for the next-to-have feature](https://github.com/inikulin/publish-please/issues/63)
