### ISSUE TITLE
Perform extra sensitive checks on published files, not on all

### ISSUE THREAD

**Issue by bahmutov** [inikulin/publish-please#2]
right now code checks every filename against a list (https://github.com/bahmutov/ban-sensitive-files) but the published files will be very different due to .npmignore, .gitignore and "files" property (see http://glebbahmutov.com/blog/smaller-published-NPM-modules/) 

I think we need to grab the actual list of published files using https://www.npmjs.com/package/pkgfiles and ban files like `.npmrc` for example. I am working on extra filename / contents audit for NPM packaged files in https://github.com/bahmutov/ban-sensitive-files/issues/7

**Comment by inikulin** [comment]
Hi. 
Yes, this makes sense. Do you mind sending a PR?

P.S. Thank you for your package, BTW, it's used by the `publish-please` internally.

**Comment by bahmutov** [comment]
I found it inside when looking how you check sensitive files. I will try making a PR, but a little short on time, but we will see

**Comment by inikulin** [comment]
@bahmutov I'll take care of this on weekend. Thank you for the suggestion!

**Comment by inikulin** [comment]
Closed via  14827a9
