### ISSUE TITLE
prepublishScript and validations

### ISSUE THREAD

**Issue by artemruts** [inikulin/publish-please#22]
Hi Ivan,

Not an issue more like a question about `publish-please`.
When I use `prebublishScript` to tag or to do other things that involve changing versions, contents of files, etc, I run multiple checks to make sure user is doing everything right. Among those checks are checks for `master` branch and if repo is `clean`. Can I create another pr to move `prepublishScript` after all the validations so users don't run same validations twice in `prepublishScript` and `publish-please`? But then again we don't want to publish anything without knowing what user's `prepiblishSscript` did to the repo...What do you think about this?

**Comment by inikulin** [comment]
You can simply disable unnecessary validations in `publish-please` using options or `.publishrc` file.

**Comment by artemruts** [comment]
Thank you, I guess in my case it'll be enough to drop some validations.
