### ISSUE TITLE
Global version

### ISSUE THREAD

**Issue by bfred-it** [inikulin/publish-please#29]
Is it possible to install it globally? I'm not sure I want to add this as a dependency to all of my packages but it looks more complete than https://www.npmjs.com/package/np

**Comment by inikulin** [comment]
It should be a dev dependency, so it's shouldn't affect your production performance. Anyway, you can use v1.0: https://github.com/inikulin/publish-please/tree/1.0 . But it's missing some features, including guard, which will prevent from publishing with `npm publish`. From my experience someone can accidently run `npm publish` and skip some important steps like Babel transpilation which results into broken package version.

**Comment by KyleAMathews** [comment]
Could you update the warning when installing globally to make it clear that isn't supported now? I tried upgrading from 1.x 5-6 times before finding this issue.

**Comment by inikulin** [comment]
@KyleAMathews Can you describe issues you've encountered in details, please?

**Comment by inikulin** [comment]
@KyleAMathews Nevermind, got it now. I've created separate issue: https://github.com/inikulin/publish-please/issues/32

**Comment by bfred-it** [comment]
@inikulin your point is valid but I'd still rather not add it to my modules, but instead use it as a cli tool when necessary.

**Comment by inikulin** [comment]
@bfred-it You are free to use v1.x.x then

**Comment by rprieto** [comment]
Hi, same question: I didn't quite understand why the global version is deprecated. What are the main reasons?

I agree most tools should be local "dev" dependencies (e.g. mocha, eslint, etc...). However this feels like a tool that I want to have on our build agents so it applies to **all** our packages. Similar to @bfred-it, having to add it to hundreds of modules in an enterprise context would be time-consuming, and also error prone (we might forget about some modules, or forget to update them...).

If it's installed globally on the build server (or in the Docker image we run to run all Node builds), then we can apply a default setting which is "how all our packages get published".

**Comment by inikulin** [comment]
Hi, this is a requirement since it allows prevent publishing without publish-please. I don't dig this argument about installation to many packages, to be honest (at least the process can be automated with a few lines of code). But if it's still a huge concern for you, then fell free to use v1 or fork current version and implement required functionality.
