### ISSUE TITLE
publish-please fails an nsp check

### ISSUE THREAD

**Issue by boneskull** [inikulin/publish-please#36]
This is due to an old version of `moment` contained in a dependency three (3) levels deep.

I have sent [a PR](https://github.com/bahmutov/ban-sensitive-files/pull/13) to address the issue, but this package will then need to update to the latest `ban-sensitive-files` when released (assuming my PR will be merged).

**Comment by inikulin** [comment]
Awesome, thanks! PR in `ban-sensitive-files` has been merged and released. Since we use semver this should be fixed just by running `npm update` in your repo.
