### ISSUE TITLE
Branch validation not working on Windows

### ISSUE THREAD

**Issue by markvandenbrink** [inikulin/publish-please#40]
Since the branch validation uses the `sed` command it won't work on Windows machines. The processing of the current branch name needs to be converted to JavaScript.

**Comment by hdorgeval** [comment]
Hi @markvandenbrink, a new version has been published that may solve your problem. Could you please give it a try?

**Comment by hdorgeval** [comment]
Hi @markvandenbrink, I close this issue. Feel free to re-open it if your problem is not solved.
