### ISSUE TITLE
Emojis broken

### ISSUE THREAD

**Issue by Xunnamius** [inikulin/publish-please#41]
The emojis don't show up on my terminal (zsh, debian, using powerline awesome fonts + source code font). Is there any way to disable them?

**Comment by inikulin** [comment]
@Xunnamius Thank you for the report!

It would be nice to gracefully degrade to text for terminals that doesn't support emojis. But I'm not aware of any method that allows us to determine if terminal supports emoji. I thought it doesn't supported by Windows (which easily can be determined by platform check), but seems like nix platforms are affected as well. In that case I guess we can get rid of emojis and use colored text instead. PR is welcome.

**Comment by inikulin** [comment]
⚠️LOOKING FOR MAINTAINERS ⚠️ Unfortunately I don't have enough time and interest in supporting this project anymore. If someone would like to step up as a maintainer for this project, please, drop a mail to ifaaan@gmail.com

**Comment by hdorgeval** [comment]
Hi @Xunnamius,   a new version has been published that may solve your problem. Could you please give it a try?

**Comment by Xunnamius** [comment]
Sure, I'll give it a go later tonight. Thanks for your hard work!

**Comment by hdorgeval** [comment]
@Xunnamius, thank you for your answer. I hope everything will be ok.

**Comment by hdorgeval** [comment]
Hi @Xunnamius, I close this issue in favor of [Vote for the next-to-have feature](https://github.com/inikulin/publish-please/issues/63)
