### ISSUE TITLE
yarn support

### ISSUE THREAD

**Issue by sobolevn** [inikulin/publish-please#42]
For now something is broken:
1. When running `yarn add publish-please` no config task is shown.
2. When running `yarn install` it fails with this message: 

> $ publish-please guard
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

[Link to the travis job](https://travis-ci.org/wemake-services/vue-material-input)

Full source code: https://github.com/wemake-services/vue-material-input

**Comment by sobolevn** [comment]
I guess it happens because: 

> prepublish: Run BEFORE the package is published. (Also run on local npm install without any arguments.)

https://docs.npmjs.com/misc/scripts

**Comment by inikulin** [comment]
Hi!

Both issues are caused by broken compatibility with npm in yarn. I've already issued a pull request to to fix this behavior: https://github.com/yarnpkg/yarn/pull/1111

**Comment by inikulin** [comment]
@sobolevn PR was merged, it should work with next yarn release

**Comment by sobolevn** [comment]
It works indeed.
