### ISSUE TITLE
Dry run mode

### ISSUE THREAD

**Issue by Couto** [inikulin/publish-please#43]
Thanks for the package. It's just awesome to have something doing so many validations with just a simple command.

I was wondering, is there a way to run the publish script in a "dry run" mode?
I would love to incorporate this in our build system to ensure that all libraries are ready to be published, but I would like to delay that to a manual process.

This implies that the `npm run publish-please -- --dry-run` would do all the same validations, except actually publishing the package.
 
Is this possible, or does it make any sense? 
Nevertheless, thanks again for this package! 👍

**Comment by inikulin** [comment]
That's a great idea. It should be easy to implement, PRs are welcome.

**Comment by inikulin** [comment]
⚠️LOOKING FOR MAINTAINERS ⚠️ Unfortunately I don't have enough time and interest in supporting this project anymore. If someone would like to step up as a maintainer for this project, please, drop a mail to ifaaan@gmail.com

**Comment by hdorgeval** [comment]
Hi @Couto , closed in favor of [Vote for the next-to-have feature](https://github.com/inikulin/publish-please/issues/63)
