### ISSUE TITLE
have an option "warn" for validations

### ISSUE THREAD

**Issue by yxliang01** [inikulin/publish-please#44]
I think it would be nice if we can set that when a validation fails, it will warn us about that without preventing us from publishing.

**Comment by inikulin** [comment]
⚠️LOOKING FOR MAINTAINERS ⚠️ Unfortunately I don't have enough time and interest in supporting this project anymore. If someone would like to step up as a maintainer for this project, please, drop a mail to ifaaan@gmail.com

**Comment by hdorgeval** [comment]
Hi @yxliang01, I close this issue in favor of [Vote for the next-to-have feature](https://github.com/inikulin/publish-please/issues/63)
