### ISSUE TITLE
Support `.publishrc.json`

### ISSUE THREAD

**Issue by AndersDJohnson** [inikulin/publish-please#47]
Support `.publishrc.json` so we get JSON syntax highlighting, linting, etc. for free.

**Comment by AndersDJohnson** [comment]
Possibly use https://github.com/davidtheclark/cosmiconfig.

**Comment by inikulin** [comment]
⚠️LOOKING FOR MAINTAINERS ⚠️ Unfortunately I don't have enough time and interest in supporting this project anymore. If someone would like to step up as a maintainer for this project, please, drop a mail to ifaaan@gmail.com

**Comment by hdorgeval** [comment]
Hi @AndersDJohnson, I close this issue in favor of [Vote for the next-to-have feature](https://github.com/inikulin/publish-please/issues/63)
