### ISSUE TITLE
[idea] Integrate `license-checker` as a new kind of validation

### ISSUE THREAD

**Issue by tobilg** [inikulin/publish-please#48]
I was thinking if it would make sense to create a new kind of validation for [license-checker](https://github.com/davglass/license-checker). Goal behind this would be that one would be able to verify if the project uses a license which is forbidden by a policy (e.g. fail on `GPL` licenses)...

**Comment by inikulin** [comment]
I love the idea. PRs are welcome!

**Comment by tobilg** [comment]
Is there any documentation on how to implement a new policy for `publish-please`?

**Comment by inikulin** [comment]
@tobilg You can take a look at how our validations are implemented: https://github.com/inikulin/publish-please/tree/master/src/validations
All you need to do is implement your validation module and add it to this list: https://github.com/inikulin/publish-please/blob/master/src/validations/index.js#L7

**Comment by tobilg** [comment]
I'll have a look! Thanks for the hints...

**Comment by tobilg** [comment]
Sorry, one more thing... How would it work when integrating the configuration of the validation module in the `.publishrc`? Thanks!

**Comment by inikulin** [comment]
Each validation has an `option` field which specifies associated `.publishrc` field. `run` method receives value specified in `.publishrc` as an argument (if it's `false` then `run` method will not be called). So, once you register your validation it should automatically appear in configuration wizard and be parsed from configuration file.

**Comment by tobilg** [comment]
Thanks, I see... I was planning to use an array/list of licenses. As far as I understood, that would work as well?!

E.g.

```javascript
{
  "licenseCheck": ["GPL", "MIT"]
}
```

And for the "online" configuration, I think I could use https://github.com/inikulin/publish-please/blob/master/src/utils/inquires.js#L29

**Comment by inikulin** [comment]
@toblig Yes, that's correct. You will get your list as an argument to `run` function.

**Comment by inikulin** [comment]
⚠️LOOKING FOR MAINTAINERS ⚠️ Unfortunately I don't have enough time and interest in supporting this project anymore. If someone would like to step up as a maintainer for this project, please, drop a mail to ifaaan@gmail.com

**Comment by hdorgeval** [comment]
Hi @tobilg, I close this issue in favor of [Vote for the next-to-have feature](https://github.com/inikulin/publish-please/issues/63)
