### ISSUE TITLE
Vulnerability reported on itself

### ISSUE THREAD

**Issue by DaveWelling** [inikulin/publish-please#49]
It looks like publish-please has a vulerability:  https://nodesecurity.io/advisories/534
It causes publishing to fail.
It would be nice if we could disable/warn for devDependency vulnerabilities.  Perhaps a config option?

**Comment by inikulin** [comment]
Yeah, it makes sense to not report vulnerabilities for devDependencies at all. PR is welcome.

**Comment by inikulin** [comment]
⚠️LOOKING FOR MAINTAINERS ⚠️ Unfortunately I don't have enough time and interest in supporting this project anymore. If someone would like to step up as a maintainer for this project, please, drop a mail to ifaaan@gmail.com

**Comment by hdorgeval** [comment]
Hi @DaveWelling, a new version has been published that may solve your problem. Could you please give it a try?

**Comment by hdorgeval** [comment]
Hi @DaveWelling, I close this issue in favor of [Vote for the next-to-have feature](https://github.com/inikulin/publish-please/issues/63)
