### ISSUE TITLE
scoped packages vs `npm publish --access <mode>`

### ISSUE THREAD

**Issue by jokeyrhyme** [inikulin/publish-please#5]
I publish scoped (yet public) packages almost exclusively now, and upstream `npm publish` requires an `--access` argument for such packages:
- https://docs.npmjs.com/cli/publish

Do you think it would be appropriate for my "public" or "restricted" access value to be recorded somewhere in .publishrc, and for `publish-please` to honour it?

Is this something you'd accept a PR for?

**Comment by inikulin** [comment]
Haven't used scoped packages yet.

> Do you think it would be appropriate for my "public" or "restricted" access value to be recorded somewhere in .publishrc, and for publish-please to honour it?

If it will not expose any credentials then why not? =)

> Is this something you'd accept a PR for?

Sure

**Comment by jokeyrhyme** [comment]
It looks like it's possible to set `{ publishConfig: { access: "public" } }` in package.json, so this might be a valid work-around:
- https://docs.npmjs.com/files/package.json#publishconfig

Also, in my experience, this only needs to be set for the first `npm publish` anyway, as a public and scoped package can be published any time after that without explicitly using `--access public`.

**Comment by inikulin** [comment]
Cool, so we can close it?

**Comment by jokeyrhyme** [comment]
Yeah, I'm sure this Issue will be easy enough to find. I do think we'll see more and more public scoped packages now that they show up in NPMs search (and as the unscoped namespace runs out of all the cool names).
