### ISSUE TITLE
Possible to pass other userconfig than the logged-in user?

### ISSUE THREAD

**Issue by tobilg** [inikulin/publish-please#50]
I would like to know if it's possible to use something similar to 

> npm publish --userconfig ~/.npmrc-myuser-config

with `publish-please`? I didn't find anything in the docs regarding that. Thanks!

**Comment by inikulin** [comment]
⚠️LOOKING FOR MAINTAINERS ⚠️ Unfortunately I don't have enough time and interest in supporting this project anymore. If someone would like to step up as a maintainer for this project, please, drop a mail to ifaaan@gmail.com

**Comment by hdorgeval** [comment]
Hi @tobilg, I close this issue in favor of [Vote for the next-to-have feature](https://github.com/inikulin/publish-please/issues/63)
