### ISSUE TITLE
be able to prevent publishing when a dependency points to github

### ISSUE THREAD

**Issue by hdorgeval** [inikulin/publish-please#56]
Hi @inikulin, I have recently published a package with publish-please (testcafe-static-analyser). But this package could not be installed inside my company due to the fact that github is not reachable on teamcity user agents.
It would be great that publish-please detect any direct dependency to github like in glob-fs (for example) and then prevents publishing.

Thanks for this great product.

**Comment by inikulin** [comment]
⚠️LOOKING FOR MAINTAINERS ⚠️ Unfortunately I don't have enough time and interest in supporting this project anymore. If someone would like to step in as a maintainer for this project, please, drop a mail to ifaaan@gmail.com

**Comment by hdorgeval** [comment]
Hi @hdorgeval, I close this issue in favor of [Vote for the next-to-have feature](https://github.com/inikulin/publish-please/issues/63)
