### ISSUE TITLE
Latest v2.4.1 on NPM doesn't run postinstall correctly

### ISSUE THREAD

**Issue by yxliang01** [inikulin/publish-please#57]
The `lib/init.js` doesn't contain any statement making `npm install --save-dev publish-please` doesn't run the configuration wizard. Since the `postinstall` script is ineffective.

Thanks

**Comment by inikulin** [comment]
⚠️LOOKING FOR MAINTAINERS ⚠️ Unfortunately I don't have enough time and interest in supporting this project anymore. If someone would like to step in as a maintainer for this project, please, drop a mail to ifaaan@gmail.com

**Comment by hdorgeval** [comment]
Hi @yxliang01, a new version has been published that may solve your problem. Could you please give it a try?

**Comment by hdorgeval** [comment]
Hi @yxliang01, I close this issue. Feel free to re-open it if your problem is not solved.
