### ISSUE TITLE
Broken git branch checking on Windows

### ISSUE THREAD

**Issue by tobilg** [inikulin/publish-please#58]
When I try to use publish-please on Windows with enabled branch validations, I see the following error message:

```bash
* Error: Command failed: git branch --no-color | sed -n '/\* /s///p'
```

`sed` is not installed by default on Windows.

**Comment by inikulin** [comment]
⚠️LOOKING FOR MAINTAINERS ⚠️ Unfortunately I don't have enough time and interest in supporting this project anymore. If someone would like to step in as a maintainer for this project, please, drop a mail to ifaaan@gmail.com

**Comment by hdorgeval** [comment]
Hi @tobilg , a new version has been published that may solve your problem. Could you please give it a try?

**Comment by hdorgeval** [comment]
Hi @tobilg, I close this issue. Feel free to re-open it if your problem is not solved
