### ISSUE TITLE
Cannot install v3.0.0 on windows

### ISSUE THREAD

**Issue by hdorgeval** [inikulin/publish-please#60]
pre-install script fails when doing an `npm install --save-dev publish-please` on windows, thus failing the install.

**Comment by inikulin** [comment]
@hdorgeval Maybe it's worth adding CI tests that run on Windows as well, e.g. using [AppVeyour](https://www.appveyor.com/)?

**Comment by hdorgeval** [comment]
Hi @inikulin, thank you for the suggestion. I am currently looking on how to setup AppVeyor on publish-please

**Comment by hdorgeval** [comment]
Solved in v3.0.1
