### ISSUE TITLE
The publish-please@3.0.0 published without the 'lib' directory

### ISSUE THREAD

**Issue by AndreyBelym** [inikulin/publish-please#62]
Check distribution tarball: https://registry.npmjs.org/publish-please/-/publish-please-3.0.0.tgz.

**Comment by hdorgeval** [comment]
Hi @AndreyBelym, v3.0.1 is now ready. Could you please give it a try?

**Comment by AndreyBelym** [comment]
Thank you for being so fast, it's fixed now.

**Comment by hdorgeval** [comment]
Hi @AndreyBelym, thank you for your feedback. I would greatly appreciate your advices on what should be in the next publish-please version : [Vote for the next-to-have feature](https://github.com/inikulin/publish-please/issues/63)

**Comment by AndreyBelym** [comment]
Thanks @hdorgeval, honestly I would like to see all of them in `publish-please` 😄 Maybe I'll implement [Github status checking](https://github.com/inikulin/publish-please/issues/63#issuecomment-395674230) and open a PR if I have some free time.
