### ISSUE TITLE
Node Security Platform shutting down

### ISSUE THREAD

**Issue by Truemedia** [inikulin/publish-please#72]
The Node Security Platform service is shutting down 9/30 - https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting

Just wondering what's the next step around this, and if this is gunna break the command after that date?

**Comment by hdorgeval** [comment]
@Truemedia : thank you for this feedback. I already reached the npm support but got no answer from them about this topic. 

Nevertheless I have found a way to programmatically  use `npm audit` command, which currently is the only official `nsp` replacer.

I will create very soon a PR on this subject in order to replace `nsp`  before the 9/30.

Best regards

**Comment by Truemedia** [comment]
@hdorgeval cool cheers

**Comment by Truemedia** [comment]
I think this deadline has passed now and publishing with this module gives me this error:
Client request error: getaddrinfo ENOTFOUND api.nodesecurity.io api.nodesecurity.io:443

**Comment by hdorgeval** [comment]
Hi @Truemedia , which version of publish-please are you using? 

From version 5.0.0, `nsp` has been replaced by a built-in validation based on `npm audit`.

you may publish using the command `npx publish-please`.

See the [Readme](https://github.com/inikulin/publish-please) for more details.

**Comment by Truemedia** [comment]
@hdorgeval Ah yes sorry that's working now. I had to do a few tweaks to my code after updating the publish-please version by reinstalling and installing due to the major version increment number aswell as other changes (creating a .sensitivedata file) and adding a "files" section to my package.json.

But all seems to be working fine now thanks, will close this ticket.

**Comment by hdorgeval** [comment]
If you are using `npx publish-please` on a project where `publish-please` has already been installed locally and if you encounter the error : 

```sh
getaddrinfo ENOTFOUND api.nodesecurity.io api.nodesecurity.io:443
```
Either uninstall the local `publish-please` and this will make the `npx publish-please` command work without error or update the local `publish-please` to latest version and continue to use the command `npm run publish-please`
