### ISSUE TITLE
Check if extra files are ignored

### ISSUE THREAD

**Issue by jehy** [inikulin/publish-please#75]
Hi! Recently I forked https://github.com/jehy/diarrhea from https://github.com/ModClean/modclean because there are often too many trash files in published package: tests, typescript files, markdown, linter configs and etc.

How about adding a check for those files? I could make a separate package but I don't want to make one more tool for the same purpose - and your tools looks just fine.

To make things easier and not write everything form scratch, you could reuse modclean or diarrhea.

**Comment by hdorgeval** [comment]
Hi @jehy, thank you for your suggestions. 
I will investigate this when PR on npm audit will be released. 
PR is also welcomed if you want to.

**Comment by hdorgeval** [comment]
Hi @jehy : I opened PR#77 to solve this issue

**Comment by hdorgeval** [comment]
Hi @jehy, `publish-version@5.0.0` has been published to npm. Could you give it a try?
Any feedback is welcomed.

**Comment by jehy** [comment]
Looks absolutely great, thanks!
It would be even better if user could override  .sensitivedata on per project basis - because there can be some files that are okay to publish and vice versa.

**Comment by hdorgeval** [comment]
Hi @jehy , thank you very much for your great feedback. I will create a PR so that you could override `.sensitivedata` on per project basis. 

I keep this issue opened until this next-to-come PR is delivered.

**Comment by hdorgeval** [comment]
Hi @jehy , your proposal has been added to publish-please@5.2.0. 
Could you give it a try?
Any feedback is welcomed.
