### ISSUE TITLE
config helper hangs on Windows after answering first question

### ISSUE THREAD

**Issue by BillyBlaze** [inikulin/publish-please#78]
Hi,

If I run `npm run publish-please config` on a windows 10 machine, then after I answered the first question, I get stuck and it will not load any follow up questions, which results that I am unable to run the config. This also happened during the first installation.

![image](https://user-images.githubusercontent.com/445608/46679973-585ad880-cbe8-11e8-8574-99bcb47c14e0.png)

I have tried this with 4.0.0 and 3.2.0 but both packages gave the same result. I also tried using different CLI (such as, powershell, nodejs cli, default windows cli) but no cigar.

Work-around: Use CMDer with bash integration (mintty)

**Comment by hdorgeval** [comment]
Hi @BillyBlaze , than you very much for this complete report. I will try to solve this issue as soon as possible.

**Comment by hdorgeval** [comment]
Hi @BillyBlaze, after investigation, this problem can only be solved by updating `inquirer` dependency to latest version. I will open a PR asap to solve this issue.

**Comment by BillyBlaze** [comment]
Hi @hdorgeval,

I have updated it to 4.0.1 and can confirm this issue has been resolved! Thanks for your hard work!
