### ISSUE TITLE
Bug: Get the error <not logged in> even though I'm logged in

### ISSUE THREAD

**Issue by crhistianramirez** [inikulin/publish-please#95]
If I run `npm whoami` it correctly returns my user and if I run `npm publish` it works. Its also a bit unfortunate that the error occurs as the last step of publishing. It would be ideal to be notified earlier in the process.

![image](https://user-images.githubusercontent.com/16483662/78376744-5e8b0480-7594-11ea-9d03-f0e74d30f053.png)

**Comment by inikulin** [comment]
afaik @hdorgeval has stepped out from the maintainer position (FIXME). So, the package currently requires a new maintainer. 

We probably should add a call for new maintainers in the README. Also, if someone reading this would like to volunteer, please let me know.

**Comment by crhistianramirez** [comment]
Ah thanks for letting me know. I probably can't commit to being the maintainer but I think this is a neat enough package that I'd like to help. I can start by digging into this bug

**Comment by hdorgeval** [comment]
Hi @inikulin , unfortunately,  I have no more time to help you on this great project; for sure I will answer any question raised on the code/tests that I have modified; 

@crhistianramirez : feel free to ask me any question if you are stuck on your PR.

**Comment by inikulin** [comment]
@hdorgeval that's alright. Thank you for all the great work you've done.

**Comment by crhistianramirez** [comment]
Turns out this happens because I was running `yarn publish-please` instead of `npm publish-please`. I was able to resolve this by logging into npm via yarn `yarn login`.

I'm closing this since its not really an issue with this package.
